/******************************************************************************/
/****         Generated by IBExpert 2006.12.13 02/05/2026 09:55:39         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

CREATE DATABASE 'C:\Users\Matheus\Desktop\TIConsultoria\DelphiLib\DataBase\TESTEFB.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_CLIENTES_ID;
SET GENERATOR GEN_CLIENTES_ID TO 1;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE CLIENTES (
    ID_CLIENTE    INTEGER NOT NULL,
    NOME_CLIENTE  VARCHAR(50),
    CPF_CLIENTE   VARCHAR(18)
);



/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE CLIENTES ADD PRIMARY KEY (ID_CLIENTE);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;


/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: CLIENTES_BI0 */
CREATE TRIGGER CLIENTES_BI0 FOR CLIENTES
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  if (NEW.id_cliente IS NULL) then
    NEW.ID_CLIENTE = gen_id(GEN_CLIENTES_ID,1);
end
^

SET TERM ; ^

